name: deploy

on: 
  push:
  branches: 
  - master

jons:
depoly: 
runs-on: ubuntu-18.04
steps: 
- uses: actions/checkout@v2
- uses: actions/setup-node@v1
with: 
node-version: '14.x'
- name: Build web-app
run: 
npm ci
cpm run build
- name: Deploy to gh-pages
uses: peaceiris/actions-gh-pages@v3
with:
github-token: ${{secrets.GITHUB_TOKEN}}
publish_dir: ./build